# Generated by Django 4.2.3 on 2023-07-17 15:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='image/user.jpg', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
