# Generated by Django 4.2.3 on 2023-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courses_tutor_student_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('mode_of_contact', models.CharField(choices=[('email', 'E-Mail'), ('phone', 'Phone')], default='email', max_length=50)),
                ('course_categories', models.CharField(choices=[('SELECT-COURSE', 'SELECT COURSE'), ('ICDL-WORK-FORCE', 'ICDL WORK FORCE'), ('ICDL-PROFESSIONAL', 'ICDL PROFESSIONAL'), ('ICDL-STUDENT', 'ICDL STUDENT'), ('ICDL-DIGITAL-CITIZEN', 'ICDL DIGITAL CITIZEN')], default='SELECT-COURSE', max_length=50)),
                ('message', models.TextField(max_length=3000)),
            ],
        ),
    ]
