# Generated by Django 4.2.3 on 2023-08-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
